version: "3.7"

services:

  nginx:
    container_name: app
    build:
      context: .
      dockerfile: ./src/app/Dockerfile
    volumes:
      - "./src/app:/usr/share/nginx/html"
    ports:
      - "80:80"
      
  flask:
    container_name: flask
    build:
      context: .
      dockerfile: ./src/flask/Dockerfile
    command: python app.py --host=0.0.0.0:8000
    volumes:
      - ./src/flask:/code
    ports:
      - "8000:8000"
      
  manage:
    container_name: manage
    build:
      context: .
      dockerfile: ./src/manage/Dockerfile
    volumes:
      - "./src/manage:/usr/share/nginx/html"
    ports:
      - "9000:9000"
